### ISSUE TITLE
Default bootstrap theme does not render full width on portrait iPhone 5S screen

### ISSUE THREAD

**Issue by mazz** [websauna/websauna#105]
See screenshot. I believe this is alpha4. Landscape OK. MobileSafari iOS10

![img_0995](https://cloud.githubusercontent.com/assets/808934/21911016/98b047ee-d8ec-11e6-8953-ec6a8f3248e0.PNG)

**Comment by miohtama** [comment]
I guess it is the link overflowing?

I know how to fix this, as I have hve this kind of issues hundreds of times. For HTML elements with very long words you need to force word break. In fact we might even need to fix this on Deform level.

**Comment by mazz** [comment]
Yes I think it's the link overflowing. 

detail.html:
```
{% extends "site/base.html" %}

{% block content %}
    <h1>title</h1>
    <h3>{{ media.title }}</h3>
    <h1>url</h1>
    <h3>{{ media.url }}</h3>
    <h1>duration</h1>
    <h3>{{ media.duration }}</h3>
    <h1>description</h1>
    <h3>{{ media.description }}</h3>
        <form class="form-fetch-audio" action="{{ 'detail'|route_url(media_uuid=media.uuid|uuid_to_slug) }}" method="post">
      <input name="csrf_token" type="hidden" value="{{ request.session.get_csrf_token() }}">
      <button type="submit" class="btn btn-default">
        Fetch Media Info
      </button>
    </form>

{% endblock %}
```

**Comment by mazz** [comment]
You know what, come to think of it if the cause the link overflow, this probably isn't a bug with websauna.
