### ISSUE TITLE
Can not find how to make model appear in admin interface

### ISSUE THREAD

**Issue by tareqalam** [websauna/websauna#11]
https://websauna.org/tutorials/gettingstarted/tutorial_09.html here in documentation:
For each model appearing in the admin interface a corresponding resource class must be created in admins.py file. question is: how to do that .. cant find an example for "Questions" model

**Comment by miohtama** [comment]
This is fixed in 4da854aea425550a5856ff56063be56996e11eeb.

Please revisit documentation now here https://websauna.org/tutorials/gettingstarted/tutorial_09.html and see if you can complete the tutorial.

Ask if anything is still unclear regarding this page.
