### ISSUE TITLE
Redis Connection Check not working for remote Host

### ISSUE THREAD

**Issue by msander** [websauna/websauna#12]
When changing the redis connection parameters, the sanity check does not work anymore.
I disabled it in my application using

init._has_redis_sessions = False

**Comment by miohtama** [comment]
@msander: Ok I'll fix this. Can you clarify what kind of parameters you are using so I can repeat 1:1?

**Comment by miohtama** [comment]
Fixed in 3f96a7652a7721c5f3c0fac064594bfa18e8e436.
