### ISSUE TITLE
simple_route doesn't work with with class method

### ISSUE THREAD

**Issue by enkidulan** [websauna/websauna#121]
In case of trying to use simple_route with class methods like that:

     class MyView:
        ...
        @simple_route("/document", route_name="document", renderer='myapp/document.html')
        def document(self):
            ...

route `document` doesn't become registered in `config` and `ws-proutes` (and in some cases`ws-pserve`) crashes with following message:

    Traceback (most recent call last):
      ...
      File "/home/enkidulan/.buildout/eggs/venusian-1.0-py3.6.egg/venusian/__init__.py", line 165, in invoke
        category_keys.sort()
    TypeError: '<' not supported between instances of 'NoneType' and 'str'

**Comment by miohtama** [comment]
Interesting. This is definitely a bug. It has somehow slipped away all these months.

**Comment by ericof** [comment]
@enkidulan: Could you test this with the latest master please?
Using the following code:

`
    from websauna.system.http import Request
    from websauna.system.core.route import simple_route

    class Views:

        def __init__(self, request: Request):
            self.request = request

        @simple_route("/", route_name="home", renderer='my.app/home.html')
        def home(self):
            """Render site homepage."""
            user = self.request.user
            is_admin = False
            if user:
                is_admin = user.is_admin()
            return {
                "project": "My Application",
                "admin": is_admin
            }`

was with **websauna/system/core/templates/site/nav.html** that looks for a route named "home"

**Comment by enkidulan** [comment]
@ericof I've tested it against the latest master and it seems to be working fine. I also added some more tests for `simple_route` - https://github.com/websauna/websauna/pull/150.

**Comment by ericof** [comment]
Closing the issue
