### ISSUE TITLE
ws-pserve error after initial setup when using --reload

### ISSUE THREAD

**Issue by chancyk** [websauna/websauna#130]
I'm receiving the following error only with the `--reload` option. This is after going through to Getting Started tutorial up to https://websauna.org/docs/tutorials/gettingstarted/tutorial_05.html:

```
LookupError: No section 'main' (prefixed by 'server') found in config...
```

I'm running Linux Mint 18.1 and Python 3.5.

**Comment by tmassman** [comment]
Having the same problem on MacOS. Removing `--reload` helps.

**Comment by s4g** [comment]
Same problem here. I had to add [server:main] section to development.ini with server parameters as well as copy [app:main] from base.ini. Looks like a problem with [include] section in ini files.

**Comment by ericof** [comment]
With the support to Pyramid 1.9, this is fixed on master.
