### ISSUE TITLE
Probable bug in IdMapper

### ISSUE THREAD

**Issue by koirikivi** [websauna/websauna#149]
https://github.com/websauna/websauna/blob/master/websauna/system/crud/urlmapper.py#L47

Unless there's some metaclass magic going on (and I don't think there is), `mapping_attribute` is class attr so setting `self.mapping_attribute` in `__init__`, will set it for the whole class (not just the instance), and will affect every instance of the class after that.

The same applies for other attributes declared in the class namespace but set in `__init__`.

**Comment by ericof** [comment]
The code sets instance attribute, not class attribute
