### ISSUE TITLE
AttributeError: 'super' has no attribute update_first_login_social_data

### ISSUE THREAD

**Issue by ericof** [websauna/websauna#155]
A pristine Google user tries to log in (no previous data).

![image](https://user-images.githubusercontent.com/306014/34539480-e81cf834-f0d0-11e7-81c4-5e232d1aeda8.jpg)

**Comment by ztane** [comment]
The fix didn't land in pre-pyramid-1.9 (which also suffered from that)

**Comment by ericof** [comment]
@ztane What is keeping you in that branch?

**Comment by ericof** [comment]
Closing this, @jsbueno will move your app to the latest release
