### ISSUE TITLE
[Feature] Allow use of translations (i18n)

### ISSUE THREAD

**Issue by arianmaykon** [websauna/websauna#18]
I know this can already be some planned feature, but it would be nice to have support for translations.

I have 3 more questions to add (not necessarily related and not necessarily right), not sure if i should create issues for them:

1. [Deform probably supports this, but i'm not sure, i'm new to Python, sorry :P] Allow customization of form (mostly login form) in the sense of buttons/text customization. Now is not possible to use another text on the login button (or translate it);
2. Allow through configuration the use of different form fields handling (mapping_item.pt), i have a feeling that [this](https://websauna.org/api/websauna.system.html#websauna.system.Initializer.configure_forms) does that, but i'm not sure;
3. Is there any forum or IRC channel (besides #pyramid) where we can discuss and ask questions about Websauna stuff in general?

I also want to give congratulations and thank you guys for this great software, i was astonished by the power an agility of it. It reminds me of some other great software i had used on another communities.

Thanks.

**Comment by miohtama** [comment]
👍 Definitely good questions.

I will set up IRC channel and answer these later today.

**Comment by arianmaykon** [comment]
I have a new more questions, maybe i'll drop them later.

**Comment by miohtama** [comment]
#3 is now being addressed https://github.com/websauna/websauna/commit/938320151c9ff6af5072cf200890bb9411a853c6

**Comment by miohtama** [comment]
I will address #1 with a paragraph in documentation.

**Comment by miohtama** [comment]
For 1. the mechanism to override is now available in #25. I'll still cover this in documentation.

**Comment by miohtama** [comment]
An example of login form customization is added in 60339d279f045292bcdf8a5775b91ec0cb134ecc.

Please see https://websauna.org/narrative/user/customize.html#customizing-user-forms

Please comment and add questions if something is still unclear.

I am going to close this issue and open a separate for i18n.

**Comment by arianmaykon** [comment]
Great, thanks a lot!
