### ISSUE TITLE
installation in opensuse 42.3

### ISSUE THREAD

**Issue by jgmtzmd** [websauna/websauna#180]
hi.
trying to install in opensuse 42.3
already installed dependencies:
Python (of course)
Redis
libxml2 (need "devel" package too)
PostgreSQL 9.6 (need "devel" package too)

but when running
`
pip install "websauna[celery,utils,notebook]"
`
i get the error..
`
    src/lxml/includes/etree_defs.h:23:32: fatal error: libxslt/xsltconfig.h: No existe el fichero o el directorio
     #include "libxslt/xsltconfig.h"

`
and here i am stuck. where do i find this xsltconfig.h ?

**Comment by jgmtzmd** [comment]
UPDATE: i was using python3.7 when the error came out. testedwith 3.6 and works fine.

**Comment by jgmtzmd** [comment]
now:
`
~/workspace/websauna $ venv/bin/pip install -e git+https://github.com/websauna/websauna.git@master#egg=websauna[celery,utils,notebook] Obtaining websauna[celery,notebook,utils] from git+https://github.com/websauna/websauna.git@master#egg=websauna[celery,utils,notebook] Updating ./venv/src/websauna clone (to revision master) Complete output from command python setup.py egg_info: Traceback (most recent call last): File <string>, line 1, in <module> File /home/jg/workspace/websauna/venv/lib/python3.6/site-packages/setuptools/__init__.py, line 10, in <module> from setuptools.extern.six.moves import filter, filterfalse, map File /home/jg/workspace/websauna/venv/lib/python3.6/site-packages/setuptools/extern/__init__.py, line 1, in <module> from pkg_resources.extern import VendorImporter File /home/jg/workspace/websauna/venv/lib/python3.6/site-packages/pkg_resources/__init__.py, line 3017, in <module> @_call_aside File /home/jg/workspace/websauna/venv/lib/python3.6/site-packages/pkg_resources/__init__.py, line 3003, in _call_aside f(*args, **kwargs) File /home/jg/workspace/websauna/venv/lib/python3.6/site-packages/pkg_resources/__init__.py, line 3045, in _initialize_master_working_set dist.activate(replace=False) File /home/jg/workspace/websauna/venv/lib/python3.6/site-packages/pkg_resources/__init__.py, line 2577, in activate declare_namespace(pkg) File /home/jg/workspace/websauna/venv/lib/python3.6/site-packages/pkg_resources/__init__.py, line 2151, in declare_namespace _handle_ns(packageName, path_item) File /home/jg/workspace/websauna/venv/lib/python3.6/site-packages/pkg_resources/__init__.py, line 2091, in _handle_ns _rebuild_mod_path(path, packageName, module) File /home/jg/workspace/websauna/venv/lib/python3.6/site-packages/pkg_resources/__init__.py, line 2120, in _rebuild_mod_path orig_path.sort(key=position_in_sys_path) AttributeError: _NamespacePath object has no attribute sort ---------------------------------------- Command python setup.py egg_info failed with error code 1 in /home/jg/workspace/websauna/venv/src/websauna/
`

**Comment by ericof** [comment]
@jgmtzmd What is your setuptools version?

**Comment by jgmtzmd** [comment]
setuptools              28.8.0 

anyway, somehow i managed to install the project but now i am trying to make postgres work. thanks.

**Comment by ericof** [comment]
As a suggestion, please use a newer version of setuptools and for psycopg2 try to install the psycopg2-binary package

**Comment by jgmtzmd** [comment]
when i try to run "venv/bin/ws-alembic .."
i keep getting the error (psycopg2.OperationalError) FATAL:  authentication failed...

but when i run this simple script
````
import psycopg2 

conn = psycopg2.connect(host="localhost", database=locura_dev) # si fxna 
cur = conn.cursor() 
cur.execute(SELECT version()) 
db_version = cur.fetchone() 
print(" . . . . ",db_version) 
cur.close() 
conn.close()
````
using the same venv it works fine. that makes me think that psycopg and postgres server are working fine. what could it be?

**Comment by jgmtzmd** [comment]
update: silly mistake: i was following the tutorial but changed some names (project, etc..) this led me make the mistake of running the commands as in the tutorial and not adapting it to my names. For noobs like me i recommend to follow the README.rst file instead of the tutorial, in the README.rst the commands are adapted to the names defined with the cookiecutter.
