### ISSUE TITLE
Does not support Windows servers

### ISSUE THREAD

**Issue by 3x0dv5** [websauna/websauna#189]
A WebSauna application doesn't seem to work on Windows at least not as a development machine. Couple of reasons:
1. Requires Redis as a session store
2. module : websauna/compat/typing.py has a posix import
          from posix import stat_result as stat_result

Could you confirm that this is the case? We cannot use a Windows machine to take the full potential of websauna?

**Comment by miohtama** [comment]
I suggest you use Windows Subsystem for Linux to run Websauna.

https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux

Windows support is not planned.

**Comment by miohtama** [comment]
For more information see https://websauna.org/docs/tutorials/gettingstarted/tutorial_01.html?highlight=windows

**Comment by 3x0dv5** [comment]
I managed to make it work on Windows, but got to get rid of the redis session store.
