### ISSUE TITLE
@simple_route break default custom notfound

### ISSUE THREAD

**Issue by slav0nic** [websauna/websauna#192]
```python
# Initializer
def configure_views(self):
      self.config.add_route('home',  '/')
      from . import views
      self.config.scan(views)

# views.py
@view_config(route_name='home', renderer='main/home.html')
def home(request: Request):
    return {"project": "Demo"}
```
If i replace `@view_config` by `@simple_route("/",  route_name="home", renderer='main/home.html')` + remove `.add_route` default websauna 404 and other view not called (i see default pyramid error).

**Comment by ericof** [comment]
@slav0nic Could you, please, add the following lines to your configuration file:
```
debugtoolbar.debug_notfound = true
pyramid.debug_notfound = false
```
And try again?
(I was not able to reproduce the error here)

**Comment by slav0nic** [comment]
it already was in my settings

**Comment by ericof** [comment]
@slav0nic I created a new app using the cookiecutter, latest Websauna, added  and with
`pyramid.debug_notfound = false`
on the config and the 404 is the one from Websauna.
