### ISSUE TITLE
websauna epub is broken?

### ISSUE THREAD

**Issue by petri** [websauna/websauna#195]
Does not open in MacOS iBooks.

**Comment by ericof** [comment]
Confirmed, will fix soon

**Comment by ericof** [comment]
Fixed. Please take a look at the new version

**Comment by petri** [comment]
I pulled master, went to docs, ran make epub & tried opening the resulting epub file in iBooks. Got the same error complaining the file is broken. This is on Macbook Pro, High Sierra.
