### ISSUE TITLE
Websauna is not compatible with redis >= 3.0? 

### ISSUE THREAD

**Issue by jaspetry** [websauna/websauna#212]
Installing the recently released redis 3.0.1, which is pulled in by pip install websauna, causes an exception to be thrown on startup (Traceback edited for length):

***********
Traceback (most recent call last):
...
File "/python3.7/site-packages/websauna/system/core/redis.py", line 137, in is_sane_redis
    redis.set("websauna_session_test", True)
...
File "/python3.7/site-packages/redis/connection.py", line 113, in encode
    raise DataError("Invalid input of type: 'bool'. Convert to a "
redis.exceptions.DataError: Invalid input of type: 'bool'. Convert to a byte, string or number first.
Server with PID 6122 exited with code 1.
***********
Running
  pip install --force-reinstall 'redis==2.10.6'
serves as a work around.

See:
https://pypi.org/project/redis/#encoding-of-user-input

**Comment by jgmtzmd** [comment]
problem persists as of january 2019.
is it a bug that should be fixed in the redis library or is there something that can be fixed in websauna code base?

**Comment by slav0nic** [comment]
redis version was pinned to `<3` in master.
Current stable Celery version don't support redis v3 too, so it will make sense after celery v5 release (or maybe 4.3)

**Comment by ericof** [comment]
I will do a release in the next days to deal with this.

**Comment by franzos** [comment]
@ericof I'm still facing issues with this. I've made _cookiecutter_ install from master using

```
git+https://github.com/websauna/websauna.git@master#egg=websauna[dev,celery,utils,notebook]
-e ".[dev,test]"
```

but running the initial migration, fails with

```
pkg_resources.ContextualVersionConflict: (redis 2.10.6 (/.../env/lib/python3.7/site-packages), Requirement.parse('redis>=3.2.0; extra == "redis"'), {'celery'})
```
