### ISSUE TITLE
Redis sanity check incompatible with redis-py version 3+

### ISSUE THREAD

**Issue by khorn** [websauna/websauna#225]
The ``websauna.system.core.redis`` module contains the following line (in the ``is_sane_redis`` function):

```python
redis.set("websauna_session_test", True)
```

Setting boolean values is no longer supported in redis-py beginning with version 3.  See here:  https://pypi.org/project/redis/
(see the section entitled: "Encoding of User Input")

An obvious workaround is to downgrade redis-py to version <3, but other packages installed with websauna seem to require redis-py 3+.

**Comment by slav0nic** [comment]
Check https://github.com/websauna/websauna/issues/212

**Comment by slav0nic** [comment]
@ericof celery 4.3 was released with support py-redis >= 3.2 version
https://github.com/celery/celery/blob/e35ef96d365db797702b68fe5bcda7e312d49566/docs/whatsnew-4.3.rst#redis-message-broker

**Comment by ericof** [comment]
Implemented by https://github.com/websauna/websauna/pull/227
