### ISSUE TITLE
Websauna.org down for last couple of days.. 

### ISSUE THREAD

**Issue by kgk** [websauna/websauna#239]
403 Forbidden
Code: AllAccessDisabled
Message: All access to this object has been disabled
RequestId: 079288B985E146DE
HostId: Gt/khURTpxN1f06CiIEhFfLgNxOpt7uFM+/f16k81kw+fDPXxEzCvedKSir1NaqxiTriTTjKHRI=

**Comment by miohtama** [comment]
Fixed. Moved the site to Netlify and they are now automatically built.

**Comment by kgk** [comment]
I think the documentation link was broken during the move.
