### ISSUE TITLE
Replace pcreate with cookiecutter

### ISSUE THREAD

**Issue by miohtama** [websauna/websauna#29]
Move to cookiecutter as it provides more robust scaffolding system.

**Comment by zupo** [comment]
@karantan and myself will be working on this

**Comment by karantan** [comment]
Because cookiecutter supports fetching template via github we can actually move the scaffolds dir and create a seperate repo just for the scaffold. This way we will have even cleaner and smaller codebase.

Thoughts?

**Comment by miohtama** [comment]
I am looking forward for this! Too bad I was not aware of cookiecutter when I started the project. There are two test modulse related to scaffolding that need to pass:

* test_scaffold_app

* test_scaffold_addon

If both passes we know new scaffolds work :)

**Comment by miohtama** [comment]
Also putting scaffolds to separate git repo makes sense.
