### ISSUE TITLE
Form documentation pyramid_deform usage inconsistencies

### ISSUE THREAD

**Issue by ncouture** [websauna/websauna#38]
In at least one [document](https://github.com/websauna/websauna/blob/master/docs/source/narrative/form/form.rst), example code demonstrates the use of ``pyramid_deform.CSRFSchema`` even though it is not made available in their import statements.

Should ``pyramid_deform.CSRFSchema`` be replaced by ``deform.Form``?

**Comment by miohtama** [comment]
Yes. I have been hunting down these old references, as `pyramid_deform` is no longer maintained, but some slipped through.

Please use Edit on Github button on documentation and submit a fix.

Thank you! 🍻

**Comment by miohtama** [comment]
Fixed.
