### ISSUE TITLE
documentation: secrets.yaml smtp_host vs smtp_server

### ISSUE THREAD

**Issue by ncouture** [websauna/websauna#50]
The documentation [suggests](https://github.com/websauna/websauna/blame/4db1fc9803bd1f94112cea1dcdbf2d231f2056b1/docs/source/tutorials/deployment/email.rst#L37) using smtp_host, this results in an error when running the myapp playbook when following the production deployment instructions.

Using smtp_server solves this error.

**Comment by miohtama** [comment]
Fixed in 64fd0970cce8b71d4f7de69f9ca5d507ee3040f3
