### ISSUE TITLE
Forbidden redirects (403) should be configurable to redirect to login and use requested url after login

### ISSUE THREAD

**Issue by arianmaykon** [websauna/websauna#51]
A nice feature some frameworks/systems have is when you request a resource without being logged, you get redirected to login page, and after logged in the systems "resumes" the original request redirecting you to it.

Its more like a improvement.

**Comment by miohtama** [comment]
This is pretty straightforward, though not implement out of the box.

* Add a view handler for HTTPForbidden, similar to HTTP 500 and 404
* Render a login form on this page if the user is not authenticated (session expired?)
* When the user posts the form on Forbidden view then call:

```
login_service.authenticate_credentials(username, password, login_source="forbidden_form", location=request.url)
```

I have happy to accept PR on this matter. The only reason the feature does not exist is my laziness.
