### ISSUE TITLE
In tutorial_10, route detail is not yet defined when it's referred in a template above

### ISSUE THREAD

**Issue by miohtama** [websauna/websauna#55]
Hi, I'm working through the tutorial right now - could work around some issues, but stuck in the middle of tutorial_10, it throws KeyError: 'No such route named detail'

**Comment by frispete** [comment]
Okay, got the concept, one has to go through the whole tutorial page.

There's a minor glitch in the myapp/detail.html template: s/question.choice_set.all/question.choices/
to get it going.

Another issue on tutorial_11: 'detail' is called 'vote' now

**Comment by miohtama** [comment]
@frispete Excellent feedback. Will fix this too.

**Comment by frispete** [comment]
@miohtama: beware, I'm in the process of going through the tutorial with rephrasing and fixing... Expect my PR later today :) Do you prefer single per file commits, or one bigger commit?

**Comment by frispete** [comment]
Here's a first pass as RFC:
[tutorial.diff.txt](https://github.com/websauna/websauna/files/361749/tutorial.diff.txt)

**Comment by miohtama** [comment]
@frispete Any pull request is welcome :) I do not have any preferences in the commit style as this is such a small project.

**Comment by miohtama** [comment]
Closing this as fixed.
