### ISSUE TITLE
Docs says to use `decode_uuid` but it's missing from codebase

### ISSUE THREAD

**Issue by enkidulan** [websauna/websauna#57]
Example app https://github.com/websauna/myapp uses `slug_to_uuid` but docs says to use `custom_predicates=(decode_uuid,)`.

**Comment by miohtama** [comment]
I removed the predicate as it turned out to be a bad practice. Cleaning up docs now.

**Comment by miohtama** [comment]
Fixed in #58a48e7da7d74c34ad05440c36964681b782736b

**Comment by enkidulan** [comment]
Docs on server doesn't seem to be updated, check this page https://websauna.org/narrative/form/autoform.html#rolling-out-your-own-view-with-field-mapper:

```
from websauna.system.core.route import decode_uuid
...
@simple_route("/edit_question/{question_uuid}",
              route_name="edit_question",
              renderer="myapp/edit_question.html",
              custom_predicates=(decode_uuid,))
```

**Comment by miohtama** [comment]
Thanks! Let me push update later today.
