### ISSUE TITLE
tutorial_10: decode_uuid does not exist

### ISSUE THREAD

**Issue by tmbb** [websauna/websauna#67]
At [tutorial_10](https://websauna.org/tutorials/gettingstarted/tutorial_10.html), we are told to import the function `websauna.system.core.route.decode_uuid()` which does not exist and which is supposedly a predicate. I managed to make it work by not using `decode_uuid()`, and changing the function to the following:

``` python
import slug_to_uuid

@simple_route("/questions/{question_uuid}",
              route_name="detail",
              renderer="myapp/detail.html")
def detail(request: Request):
    question_uuid = slug_to_uuid(request.matchdict['question_uuid'])
    question = request.dbsession.query(Question).filter_by(uuid=question_uuid).first()
    if not question:
        raise HTTPNotFound()
    return dict(question=question)
```

I will not submit a pull request because I'm not sure what the example was trying to accomplish (I'm not familiar with pyramid route predicates yet), and this is just a simple workaround.

**Comment by tmbb** [comment]
Also, in the tutorial version, `detail` accepts two arguments, the second of which is the `question_uuid`. I get an error in which according to inspection by the debug toolbar `request` is matched to the application Root and `question_uuid` is mapped to the request variable. i don't really understand why.

**Comment by miohtama** [comment]
Fixed now. This was due to old @simple_route behavior that now has been git rid off.
