### ISSUE TITLE
tutorial_10: error in detail.html

### ISSUE THREAD

**Issue by tmbb** [websauna/websauna#68]
rendering of the `'myapp/detail.html'` template fails with the following error:

``` python
jinja2.exceptions.UndefinedError: 'myapp.models.Question object' has no attribute 'choice_set'
```

I guess this is because the `Question` class attributes have been changed, and `choice_set` is now `choices`. My git archeology skills are not good enough to search for the changeset in which this was changed.

**Comment by miohtama** [comment]
Fixed now.
