### ISSUE TITLE
tutorial_10: talk about websauna's template context variables

### ISSUE THREAD

**Issue by tmbb** [websauna/websauna#69]
In the `question.html` template, the `uuid_to_slug` filter is used without being explicitly supploed as an argument. Even though this is probably obvious to anyone who has worked with Jinja2 before, in my opinion it would be good to talk about the fact that Websauna injects some variables and filters into the templates, and perhaps add a direct link to the relevant documentation section.

**Comment by miohtama** [comment]
Fixed in b25213b
