### ISSUE TITLE
error running pip install websauna

### ISSUE THREAD

**Issue by tareqalam** [websauna/websauna#7]
(venv)  xxx@xxx  ~/DATA/webprojects/myproject  pip install websauna     
Collecting websauna
  Could not find a version that satisfies the requirement websauna (from versions: )
No matching distribution found for websauna
Any idea why its happening?
but this seems working:
pip install -e "git+https://github.com/websauna/websauna.git@master#egg=websauna"

**Comment by miohtama** [comment]
This is because `websauna` package has not been released on PyPi yet and only available as version zero (unrelease) on Github.
