### ISSUE TITLE
Don't require manual CREATE EXTENSION IF NOT EXISTS "uuid-ossp"

### ISSUE THREAD

**Issue by miohtama** [websauna/websauna#72]
Currently when running Websauna on PSQL database you want to use `uuid-ossp` extension for UUID column. However to get this support for the database one needs to run command:

```
  psql -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; CREATE EXTENSION IF NOT EXISTS "postgis";' mydbname
```

This is an unnecessary manual step. Websauna should come with prepopulated Alembic migration script that does this as the initial Alembic migration. 

`ws-sync-db` command already does this for you.

However one needs to check for the database type, as this won't work on SQLite.

**Comment by corehack** [comment]
Please correct me if i'm wrong, I thought the extension was not needed since we can always safely generate UUID in the application.

**Comment by ericof** [comment]
Already implemented
