### ISSUE TITLE
Consistently use single or double queotes

### ISSUE THREAD

**Issue by karantan** [websauna/websauna#76]
I'm not sure if this is on purpose but somewhere single quotes are used for strings and somewhere there are double quotes. 

IMO it makes sense to use only single or only double quotes. Thoughts?

**Comment by miohtama** [comment]
Double quotes should be the default.

If there a single quotes somewhere it's usually because

* The original source code comes from tutorials using single quotes

* Single quotes were in scaffold used to create Websauna

**Comment by karantan** [comment]
OK so if I see single quotes I can replace them with double quotes? e.g. https://github.com/websauna/websauna/blob/master/websauna/utils/configincluder.py#L54

**Comment by miohtama** [comment]
Yes please!

**Comment by miohtama** [comment]
Closing this as ongoing process.
