### ISSUE TITLE
Docs: sphinx can't get objects.inv

### ISSUE THREAD

**Issue by tmbb** [websauna/websauna#84]
Sphinx can't get `objects.inv` from websauna's docs (403 error). If you point the browser at
`https://websauna.org/docs/objects.inv` you can download the file without problems.

**Comment by miohtama** [comment]
Can you clarify what you are trying to do? Is this some Sphinx command you run?

**Comment by tmbb** [comment]
I'm running a simple ``make html`` using sphinx while using the following ``intersphinx_mapper``:

```python
intersphinx_mapping = {
    'https://docs.python.org/3.5': None,
    'sqlalchemy': ('http://docs.sqlalchemy.org/en/latest', None),
    'websauna': ('https://websauna.org/docs/', None)
  }
```

```bash
loading intersphinx inventory from https://websauna.org/docs/objects.inv...
WARNING: intersphinx inventory 'https://websauna.org/docs/objects.inv' not fetchable due to <class 'urllib.error.HTTPError'>: HTTP Error 403: Forbidden
```
 When I access ``https://websauna.org/docs/objects.inv`` using the browser I can download the file without any problems. My workaround is to download the file using the browser and placing it at ``inventories/websauna/objects.inv``.
Then, I can add a local path for the intersphinx mapper:

```python
intersphinx_mapping = {
    'https://docs.python.org/3.5': None,
    'sqlalchemy': ('http://docs.sqlalchemy.org/en/latest', None),
    'websauna': ('https://websauna.org/docs/', 'inventories/websauna/objects.inv')
  }
```

**Comment by miohtama** [comment]
It must be Cloudflare.

**Comment by miohtama** [comment]
I turned Cloudflare Security off. Please tell me if it runs for you for now.

**Comment by ericof** [comment]
Working now
