### ISSUE TITLE
pyramid_mailer doesn't like Celery

### ISSUE THREAD

**Issue by miohtama** [websauna/websauna#85]
pyramid_mailer assumes thread local transaction manager. This does not work with Celery. You cannot rely on commit hook to send out email, because it's using wrong transaction manager.

See `send_templated_mail()` for the current workaround.

**Comment by Infernion** [comment]
@miohtama As I saw, bug related to the pyramid_mailer was closed. So is it mean that this issue no more exists for websauna?

**Comment by miohtama** [comment]
I think I still need to update the function call to use new `pyramid_mailer` interface that passes transaction manager around.

**Comment by ericof** [comment]
Not using pyramid_mailer anymore.
