### ISSUE TITLE
SocialLoginMapper -> separate ABC and Interface to their own classes

### ISSUE THREAD

**Issue by miohtama** [websauna/websauna#98]
https://github.com/websauna/websauna/blob/master/websauna/system/user/social.py#L22

**Comment by ztane** [comment]
The fix is *incorrect* in pre-pyramid-1.9 branch!

**Comment by ericof** [comment]
@ztane Any other information? And again, could you move to the released version?

**Comment by ericof** [comment]
Closing this, @jsbueno will move your app to the latest release
